name: Build
on: [ push ]
jobs:
  build:
    name: Build
    runs-on: self-hosted
    if: github.actor == github.repository_owner
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v2
        name: Setup Java environment
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.3
        with:
          maven-version: 3.8.2
      - name: Maven verify & package
        run: mvn --update-snapshots verify org.pitest:pitest-maven:mutationCoverage -Ptest
        env:
          DOCKER_HOST: unix:///var/run/docker.sock
      - uses: sonarsource/sonarqube-scan-action@master
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.PROJECT_KEY }}
            -Dsonar.branch.name=${{ github.ref_name }}
            -Dsonar.java.binaries=target/classes
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}